
import os
print("Hello In MY Tool")
os.system ("clear")
print ("This Tool Made Py (Guest Hacker)")
print ("Best Hacking Tool In Termux And KALI LINUX")
a = input ("Pls Type Tool Password: ")
print (a)
if a == "Guest Hacker" :
    print ("Corect")
else:
  print ("Error..!")
ad = input ("Pls Type Tool Password: ")
if ad == "Guest Hacker" :
  print ("Corect")
else:
  print ("Error..!")
os.system ("clear")
ae = ("What U Want?")
ar = ("[1]Spam Tool&&WebSite")
af = ("[2]Hack App&&Tool")
ad = ("[3]About")
ax = ("[4]Exit")
print (ae)
print (ar)
print (af)
print (ad)
print (ax)
at = input ("Type What You Want 1&2&3&4: ")
if at == "1" :
    os.system ("clear")
    print ("Wepsites")
    print ("1=Sp0m")
    print ("2=anomor")
    print ("3=z-shadow")
    print ("4=Jokerdz")
    print ("4=waspami")
    print ("5=smikta")
    print ("6=shraidar")
    print ("7=dev-point")
    print ("8=hamza dz")
    print ("Tools")
    print ("1=v7x phishing")
    print ("2=zphisher")
    print ("3=Nexphisher")
    print ("4=socialfish")
    print ("Please copy the name and search for the tool")
if at == "2" :
  print ("Apps")
  print ("1=metasploit")
  print ("2=nmap")
  print ("3=kali nethunter")
  print ("4=kali linux")
  print ("5=zanti")
  print ("6=DroidSheep")
  print ("7=Network Spoofer")
  print ("8=DSploit")
  print ("AndroRat")
  print ("Tools")
  print ("1=Tool-X")
  print ("2=DarkFly-Tool")
  print ("3=PhoneSploit")
  print ("4=RedHawk")
  print ("5=sqlmap")
  print ("6=EasY_HaCk")
  print ("7=Card-Numper")
  print ("8=TBomb")
  print ("9=Vbug")
  print ("10=ngrok")
  print ("11=RouterSploit")
  print ("12=Call")
  print ("13=Hammer")
  print ("Please copy the name and search for the tool")
if at == "3" :
    print ("This Tool TO Best Hacking Tool And Spam this not install this name for best hacking tool and spam you search to tool or website or app")
    if at == "4" :
        print ("ctrl+C")
